name: ton_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  ton_core:
    git:
      url: https://github.com/voledyaev/ton_core.git
  auto_route: ^2.2.0
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.1
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  injectable: ^1.3.0
  json_annotation: ^4.0.1
  logger: ^1.0.0
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  freezed: ^0.14.1+3
  hive_generator: ^1.1.0
  injectable_generator: ^1.3.0
  json_serializable: ^4.1.1
  lint: ^1.5.3

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#448aff"
